version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/code
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/nginx
    restart: unless-stopped

  php:
    container_name: php
    image: php:fpm
    ports:
      - "9000:9000"
    build:
      context: dockerfile
      dockerfile: php
    volumes:
      - ./app:/code
      - ./conf/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
      - ./conf/php.conf:/usr/local/etc/php-fpm.d/php.conf
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    restart: unless-stopped

  nginxalt:
    container_name: nginxalt
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8843:8843"
    volumes:
      - ./www:/code
      - ./conf/nginxalt.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/nginx
    restart: unless-stopped

  phpalt:
    container_name: phpalt
    image: php:fpm
    ports:
      - "9090:9090"
    build:
      context: dockerfile
      dockerfile: phpalt
    volumes:
      - ./www:/code
      - ./conf/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
      - ./conf/php.conf:/usr/local/etc/php-fpm.d/php.conf
      - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./conf/phpalt-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    build:
      context: dockerfile
      dockerfile: mysql
    volumes:
      - ./mysql/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dashboard_adm
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8082:80"
    volumes:
      - ./conf/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=mysql
    restart: unless-stopped
